import type { ContentValue } from '@ainam/schema/types'
import { AinamError } from './errors'

/**
 * Content captured at build time and shipped with the site.
 *
 * This is what keeps a customer's site up while the CMS is not: the client
 * falls back to it whenever a request fails. Generate it with `ainam pull`.
 */
export interface ContentSnapshot {
  projectId: string
  locale: string
  /** ISO timestamp of when the snapshot was generated. */
  generatedAt: string
  entries: Record<string, ContentValue>
}

/** Narrowing type guard, so a hand-written or stale snapshot fails loudly. */
export function isContentSnapshot(value: unknown): value is ContentSnapshot {
  if (typeof value !== 'object' || value === null) return false
  const candidate = value as Partial<ContentSnapshot>
  return (
    typeof candidate.projectId === 'string' &&
    typeof candidate.locale === 'string' &&
    typeof candidate.generatedAt === 'string' &&
    typeof candidate.entries === 'object' &&
    candidate.entries !== null
  )
}

/**
 * Narrows an imported snapshot file.
 *
 * TypeScript widens the string literals in an imported `.json`, so
 * `"type": "doc"` arrives as `string` and stops matching `RichTextValue` — the
 * file is correct and the type is not. This checks the shape at runtime and
 * returns it typed, which is both the fix and a guard against a snapshot that
 * was hand-edited or generated by an older CLI.
 *
 * @example
 * ```ts
 * import snapshotFile from '../ainam-snapshot.en.json'
 *
 * export const ainam = createAinamContent<AinamContent>({
 *   // …
 *   snapshot: contentSnapshot(snapshotFile),
 * })
 * ```
 */
export function contentSnapshot(value: unknown): ContentSnapshot {
  if (isContentSnapshot(value)) return value
  throw new AinamError(
    'config_invalid',
    'That is not an AINAM content snapshot. Regenerate it with "ainam pull".',
  )
}
