// Generated by `ainam pull` or `ainam generate`. Do not edit.
//
// Regenerate after the schema changes. Passing this to createAinamClient turns
// a wrong content key into a compile error.

// A type alias, not an interface: TypeScript gives an alias an implicit index
// signature but withholds one from an interface, so an interface fails the
// `T extends ContentMap` constraint on createAinamClient and every consumer
// would see that error on every build.
export type AinamContent = {
  /** Footer links — Grouped by the column heading. A new heading creates a new column. */
  "footer/links": Array<{
    "href": string
    "group": string
    "label": string
  }>
  /** Status label — Only truthful if something actually checks it. Off by default for that reason. */
  "footer/status/label": string
  /** Show the status badge */
  "footer/status/visible": boolean
  /** Footer tagline */
  "footer/tagline": string
  /** Closing primary button */
  "home/cta/primary": string
  /** Closing secondary button */
  "home/cta/secondary": string
  /** Closing heading, second line */
  "home/cta/subtitle": string
  /** Closing heading */
  "home/cta/title": string
  /** Features — paragraph */
  "home/features/body": string
  /** Features — eyebrow */
  "home/features/eyebrow": string
  /** Feature cards — Icon names come from lucide.dev. An unknown name falls back to a plain square. */
  "home/features/items": Array<{
    "body": string
    "icon": string
    "title": string
  }>
  /** Features — heading */
  "home/features/title": string
  /** Announcement badge */
  "home/hero/announcement/tag": string
  /** Announcement text */
  "home/hero/announcement/text": string
  /** Show the announcement pill — The badge above the headline. Switch it off between announcements. */
  "home/hero/announcement/visible": boolean
  /** Hero paragraph */
  "home/hero/body": string
  /** Primary button */
  "home/hero/cta/primary": string
  /** Secondary button */
  "home/hero/cta/secondary": string
  /** Install line — The mono caption under the buttons. */
  "home/hero/install": string
  /** Headline, second line */
  "home/hero/subtitle": string
  /** Headline — The first line. The second line is a separate key and renders dimmer. */
  "home/hero/title": string
  /** How it works — paragraph */
  "home/how/body": string
  /** How it works — eyebrow */
  "home/how/eyebrow": string
  /** Steps — Numbered 01, 02, 03 in order. The code block is optional. */
  "home/how/steps": Array<{
    "body": string
    "code": string
    "title": string
    "filename": string
  }>
  /** How it works — heading */
  "home/how/title": string
  /** Logo wall caption */
  "home/logos/label": string
  /** Customer names — Set in mono, one per entry. Add a name only with their permission. */
  "home/logos/names": Array<{
    "name": string
  }>
  /** Show the customer logos — Off until the names below are real customers who agreed to be named. */
  "home/logos/visible": boolean
  /** Publishing — paragraph */
  "home/publish/body": string
  /** Publishing — eyebrow */
  "home/publish/eyebrow": string
  /** Publishing — heading */
  "home/publish/title": string
  /** Who said it */
  "home/testimonial/name": string
  /** Quote */
  "home/testimonial/quote": string
  /** Their role */
  "home/testimonial/role": string
  /** Show the quote — Off until the quote below is one a real customer actually gave us. */
  "home/testimonial/visible": boolean
  /** Header button */
  "nav/cta": string
  /** Header links — Shown between the wordmark and the sign-in link. */
  "nav/links": Array<{
    "href": string
    "label": string
  }>
}

/** Every key in this project's schema, for exhaustiveness checks. */
export type AinamContentKey = keyof AinamContent
