import type { ContentSchema } from '@ainam/core'
import { describe, expect, it } from 'vitest'
import { generateContentTypes } from '../src/codegen'

const schema: ContentSchema = {
  'home/hero/title': { type: 'text', label: 'Hero title', required: true, multiline: false, default: 'T' },
  'home/hero/body': { type: 'richText', label: 'Hero body', required: false, default: 'B' },
  'home/hero/image': { type: 'image', label: 'Hero image', required: false, alt: true },
  'home/pricing/visible': { type: 'boolean', label: 'Show pricing', required: false, default: true },
  'home/pricing/seats': { type: 'number', label: 'Seats', required: false, default: 3 },
}

describe('generateContentTypes', () => {
  const output = generateContentTypes(schema)

  it('emits a type alias, not an interface', () => {
    // An interface has no implicit index signature, so it fails the
    // `T extends ContentMap` constraint and every consumer sees that error.
    expect(output).toContain('export type AinamContent = {')
    expect(output).not.toContain('export interface AinamContent')
  })

  it('maps each field kind to the type its stored value actually has', () => {
    expect(output).toContain('"home/hero/title": string')
    expect(output).toContain('"home/hero/body": RichTextValue')
    expect(output).toContain('"home/pricing/visible": boolean')
    expect(output).toContain('"home/pricing/seats": number')
  })

  it('types an image as nullable, since it is the one kind without a default', () => {
    expect(output).toContain('"home/hero/image": ImageValue | null')
  })

  it('sorts keys so a regenerated file differs only where the schema did', () => {
    const order = ['home/hero/body', 'home/hero/image', 'home/hero/title']
    const positions = order.map((key) => output.indexOf(`"${key}"`))
    expect(positions).toEqual([...positions].sort((a, b) => a - b))
  })

  it('says the file is generated, so nobody edits it by hand', () => {
    expect(output.split('\n')[0]).toMatch(/Generated by/)
  })

  it('carries each field label through as documentation', () => {
    expect(output).toContain('/** Hero title */')
  })

  it('expands a list field into the shape of its items', () => {
    const withList = generateContentTypes({
      'home/logos': {
        type: 'list',
        label: 'Logos',
        required: false,
        default: [],
        fields: {
          alt: { type: 'text', label: 'Alt', required: true, multiline: false, default: '' },
          src: { type: 'image', label: 'Logo', required: true, alt: true },
        },
      },
    })
    expect(withList).toContain('"alt": string')
    expect(withList).toContain('"src": ImageValue | null')
    expect(withList).toContain('Array<{')
  })
})

describe('generated imports', () => {
  it('imports only the helper types the schema actually uses', () => {
    const textOnly = generateContentTypes({
      'a/b': { type: 'text', label: 'A', required: false, multiline: false, default: '' },
    })
    // An unused import fails noUnusedLocals, and generated code must never be
    // the thing that breaks a consumer's build.
    expect(textOnly).not.toContain("from '@ainam/core'")

    const withImage = generateContentTypes({
      'a/b': { type: 'image', label: 'A', required: false, alt: true },
    })
    expect(withImage).toContain("import type { ImageValue } from '@ainam/core'")
    expect(withImage).not.toContain('RichTextValue')
  })
})
