import type { ContentSchema, Field, ScalarField } from '@ainam/core'

/** The TypeScript type a field's stored value has. */
function typeOfScalar(field: ScalarField): string {
  switch (field.type) {
    case 'text':
      return 'string'
    case 'richText':
      return 'RichTextValue'
    case 'boolean':
      return 'boolean'
    case 'number':
      return 'number'
    case 'image':
      // Resolved, not stored: the content API splices in the URL and the
      // intrinsic dimensions, so a site can lay out the space before the image
      // loads. Nullable because this is the one kind with no default, so the
      // site has to handle an image nobody has uploaded yet.
      return 'ResolvedImage | null'
  }
}

function typeOfField(field: Field): string {
  if (field.type !== 'list') return typeOfScalar(field)
  const shape = Object.entries(field.fields)
    .map(([name, item]) => `    ${JSON.stringify(name)}: ${typeOfScalar(item)}`)
    .join('\n')
  return `Array<{\n${shape}\n  }>`
}

/**
 * Turns a project's schema into a TypeScript module.
 *
 * This is what makes a wrong content key a compile error rather than a blank
 * section: the generated map is passed to `createAinamClient<AinamContent>()`,
 * so `get` only accepts keys that exist and returns each one's real type.
 *
 * The output is written, not hand-edited, so it carries a header saying so and
 * the keys are sorted — a regenerated file should differ only where the schema
 * did.
 */
export function generateContentTypes(schema: ContentSchema): string {
  const keys = Object.keys(schema).sort()

  const entries = keys
    .map((key) => {
      const field = schema[key]
      if (!field) return ''
      const doc = field.description ? `  /** ${field.label} — ${field.description} */\n` : `  /** ${field.label} */\n`
      return `${doc}  ${JSON.stringify(key)}: ${typeOfField(field)}`
    })
    .filter(Boolean)
    .join('\n')

  // Import only what this schema actually references. Emitting both
  // unconditionally makes the generated file fail `noUnusedLocals` in any
  // project that has it on — generated code must never be the thing that breaks
  // someone's build.
  const helpers = ['ResolvedImage', 'RichTextValue'].filter((name) => entries.includes(name))
  const importLine =
    helpers.length > 0 ? `import type { ${helpers.join(', ')} } from '@ainam/core'\n\n` : ''

  return `// Generated by \`ainam pull\` or \`ainam generate\`. Do not edit.
//
// Regenerate after the schema changes. Passing this to createAinamClient turns
// a wrong content key into a compile error.
${importLine}
// A type alias, not an interface: TypeScript gives an alias an implicit index
// signature but withholds one from an interface, so an interface fails the
// \`T extends ContentMap\` constraint on createAinamClient and every consumer
// would see that error on every build.
export type AinamContent = {
${entries}
}

/** Every key in this project's schema, for exhaustiveness checks. */
export type AinamContentKey = keyof AinamContent
`
}
