export const USAGE = `ainam — content schema tooling for AINAM projects

Usage
  ainam init            Create ainam.config.ts and add the required env keys
  ainam push            Upload the schema in ainam.config.ts to the CMS
  ainam pull            Generate types and a content snapshot per locale
  ainam generate        Generate types from ainam.config.ts, no server needed

Push options
  --locales <list>          Comma-separated locales, default "en"
  --default-locale <code>   Falls back to the first locale

Generated by pull
  ainam.gen.ts                   Typed content map — pass it to createAinamClient
  ainam-snapshot.<locale>.json   Build-time fallback, served if the CMS is down

Environment (read from .env or the shell)
  AINAM_API_KEY         schema:write to push, content:read is enough to pull
  AINAM_PROJECT_ID      The project to push to
  AINAM_URL             CMS server origin, defaults to AINAM Cloud

Options
  -h, --help            Show this message
  -v, --version         Show the installed version
`
